[package]
name = "gameboy-emulator"
version = "0.1.0"
authors = ["anden3"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
